### ISSUE TITLE
BitWarden can't read exported CSVs

### ISSUE THREAD

**Issue by bmn001** [cfbao/lastpass-vault-parser#2]
I think something may have changed in the four years since this tool was first developed.

I've got my Lastpass vault, decrypted it to CSVs successfully using this tool, and am trying to [import it into Bitwarden](https://vault.bitwarden.com/#/tools/import).

Bitwarden will not import the data.  It will only error out with the message "Data is not formatted correctly. Please check your import file and try again."  This happens whether I try to use SitesFormFields.csv or the much-larger Sites_and_SecureNotes.csv.

**Comment by cfbao** [comment]
This script was never meant to support importing into other password managers. It's only meant to help you inspect your vault and extract extra data manually.

Please use LastPass's official export feature to create a CSV that can be imported.
